version: 1.4
paths:
  s3_base_url: "https://sagemaker-eu-west-1-100701698608.s3.eu-west-1.amazonaws.com/reddit_graph_data/test"
  kps_filename: "topics_comments.pkl"

dates:
  days_before_today: 1

graph_settings:
  n_days: 5

paginator:
  comments_per_page: 3
